### ISSUE TITLE
Problem with datafield tabs since 1.6.0

### ISSUE THREAD

**Issue by adrienjacob** [magedeveloper/dataviewer#6]
After testing 1.6.0, I cannot edit / create records anymore ("Please configure tabs and assign fields in the datatype"), unless I create at least one tab for each existing datatype. Until now, all my fields were located on the default "General" tab, which was good enough...
I'm wondering whether this additional configuration step is really necessary ? Especially because we already define the fields to include in a given datatype, so it feels somewhat redundant...
Otherwise thanks for the great work, we'll hopefully soon go live.

**Comment by magedeveloper** [comment]
Hi Adrien,

Tabs need a reconfiguration because everthing relating tabs has moved to the Datatype instead in every field. Each field had to have the same tab name and you never weren't sure if that was correct. Now you only need to set up a tab once and assign the according fields. Its sure a bit redundant with the assigned fields on top of this configuration but it is necessary to get more speed on loading fields.

**Comment by adrienjacob** [comment]
Ok thanks for your answer Bastian !
